#
# RouterOS EoIP tunnel-builder 
#
- name: eoip_config
  tags: eoip
  include_vars: vars/routeros_tunnel.yaml


#
# *** Un-deploy tasks ***
#
- name: eoip_remove_spoke
  tags: eoip
  routeros_command:
    commands:
      - /interface bridge port remove [find interface={{ item.end_intf }}]
      - /interface bridge port remove [find interface=eoip-{{ item.service_id }}-{{ item.tun_id }}]
      - /interface eoip remove [find name=eoip-{{ item.service_id }}-{{ item.tun_id }}]
      - /interface bridge remove [find name=br-{{ item.service_id }}]
  loop: "{{ ros_tunnel }}"
  when:
    - item.type == "eoip"
    - item.state == "absent"
    - item.end_node == inventory_hostname


# un-deploy on hub L2T
- name: eoip_remove_hub_l2t
  tags: eoip
  routeros_command:
    commands:
      - /interface bridge port remove [find interface=eoip-{{ item.service_id }}-{{ item.tun_id }}]
      - /interface eoip remove [find name=eoip-{{ item.service_id }}-{{ item.tun_id }}]
  loop: "{{ ros_tunnel }}"
  when:
    - item.service_type == "l2t"
    - item.type == "eoip"
    - item.state == "absent"
    - item.hub_node == inventory_hostname


# un-deploy on hub L3T
- name: eoip_remove_hub_l3t
  tags: eoip
  routeros_command:
    commands:
      - /ip address remove [find interface=eoip-{{ item.service_id }}-{{ item.tun_id }}]
      - /interface list member remove [find interface=eoip-{{ item.service_id }}-{{ item.tun_id }}]
      - /interface eoip remove [find name=eoip-{{ item.service_id }}-{{ item.tun_id }}]
  loop: "{{ ros_tunnel }}"
  when:
    - item.service_type == "l3t"
    - item.type == "eoip"
    - item.state == "absent"
    - item.hub_node == inventory_hostname


#
# *** Deploy tasks ***
#

- name: eoip_deploy_spoke
  tags: eoip
  routeros_command:
    commands:
      - /interface bridge add name=br-{{ item.service_id }} arp=disabled \
        comment="{{ item.service_type }};{{ item.service_id }};{{ item.tun_id }};{{ item.comment }}"
      - /interface eoip add name=eoip-{{ item.service_id }}-{{ item.tun_id }} {{ eoip_options }} remote-address=0.0.0.0 tunnel-id=0
      - /interface eoip set [find name=eoip-{{ item.service_id }}-{{ item.tun_id }}] arp=disabled disabled=no \
        local-address={{ lookup('dig', item.end_node) }} \
        remote-address={{ lookup('dig', item.hub_node) }} \
        tunnel-id={{ item.service_id }}{{ item.tun_id }} \
        comment="{{ item.service_type }};{{ item.service_id }};{{ item.tun_id }};{{ item.comment }}"
      - /interface bridge port add bridge=br-{{ item.service_id }} interface=eoip-{{ item.service_id }}-{{ item.tun_id }}
      - /interface bridge port add bridge=br-{{ item.service_id }} interface={{ item.end_intf }}
  loop: "{{ ros_tunnel }}"
  when:
    - item.type == "eoip"
    - item.state == "new"
    - item.end_node == inventory_hostname


# deploy on hub L2T
- name: eoip_deploy_hub_l2t
  tags: eoip
  routeros_command:
    commands:
      - /interface eoip add name=eoip-{{ item.service_id }}-{{ item.tun_id }} {{ eoip_options }} remote-address=0.0.0.0 tunnel-id=0
      - /interface eoip set [find name=eoip-{{ item.service_id }}-{{ item.tun_id }}] arp=disabled disabled=no \
        local-address={{ lookup('dig', item.hub_node) }} \
        remote-address={{ lookup('dig', item.end_node) }} \
        tunnel-id={{ item.service_id }}{{ item.tun_id }} \
        comment="{{ item.service_type }};{{ item.service_id }};{{ item.tun_id }};{{ item.comment }}"
      - /interface bridge port add bridge=br-{{ item.service_id }} interface=eoip-{{ item.service_id }}-{{ item.tun_id }} 
  loop: "{{ ros_tunnel }}"
  when:
    - item.service_type == "l2t"
    - item.type == "eoip"
    - item.state == "new"
    - item.hub_node == inventory_hostname


# deploy on hub L3T
- name: eoip_deploy_hub_l3t
  tags: eoip
  routeros_command:
    commands:
      - /interface eoip add name=eoip-{{ item.service_id }}-{{ item.tun_id }} {{ eoip_options }} remote-address=0.0.0.0 tunnel-id=0
      - /interface eoip set [find name=eoip-{{ item.service_id }}-{{ item.tun_id }}] arp=enabled disabled=no \
        local-address={{ lookup('dig', item.hub_node) }} \
        remote-address={{ lookup('dig', item.end_node) }} \
        tunnel-id={{ item.service_id }}{{ item.tun_id }} \
        comment="{{ item.service_type }};{{ item.service_id }};{{ item.tun_id }};{{ item.comment }}"
      - /interface list member add list=vrf-{{ item.service_id }} interface=eoip-{{ item.service_id }}-{{ item.tun_id }}
      - /ip address add address={{ item.hub_address }} interface=eoip-{{ item.service_id }}-{{ item.tun_id }}
  loop: "{{ ros_tunnel }}"
  when:
    - item.service_type == "l3t"
    - item.type == "eoip"
    - item.state == "new"
    - item.hub_node == inventory_hostname



