#
# RouterOS EoIP tunnel-builder 
#
- name: eoip_config
  tags:
    - eoip
  include_vars: vars/routeros_tunnel.yaml


#
# un-deploy tasks
#
- name: eoip_remove_spoke
  tags:
    - eoip
  routeros_command:
    commands:
      - /interface bridge port remove [find interface={{ item.end_intf }}]
      - /interface bridge port remove [find interface=eoip-{{ item.service_id }}-{{ item.tun_id }}]
      - /interface eoip remove [find name=eoip-{{ item.service_id }}-{{ item.tun_id }}]
      - /interface bridge remove [find name=br-{{ item.service_id }}]
  loop: "{{ ros_tunnel }}"
  when: 
    - item.type == "eoip"
    - item.state == "absent"
    - item.end_node == inventory_hostname


# un-deploy on hub bridge
- name: eoip_remove_hub_br
  tags:
    - eoip
  routeros_command:
    commands:
      - /interface bridge port remove [find interface=eoip-{{ item.service_id }}-{{ item.tun_id }}]
      - /interface eoip remove [find name=eoip-{{ item.service_id }}-{{ item.tun_id }}]
  loop: "{{ ros_tunnel }}"
  when:
    - item.service_type == "br"
    - item.type == "eoip"
    - item.state == "absent"
    - item.hub_node == inventory_hostname

# un-deploy on hub vrf
- name: eoip_remove_hub_vrf
  tags:
    - eoip
  routeros_command:
    commands:
      - /ip address remove [find interface=eoip-{{ item.service_id }}-{{ item.tun_id }}]
      - /interface list member remove [find interface=eoip-{{ item.service_id }}-{{ item.tun_id }}]
      - /interface eoip remove [find name=eoip-{{ item.service_id }}-{{ item.tun_id }}]
  loop: "{{ ros_tunnel }}"
  when:
    - item.service_type == "vrf"
    - item.type == "eoip"
    - item.state == "absent"
    - item.hub_node == inventory_hostname


#
# deploy tasks
#
- name: eoip_deploy_spoke
  tags:
    - eoip
  routeros_command:
    commands:
      - /interface bridge add name=br-{{ item.service_id }} arp=disabled protocol=none \
        comment="{{ item.service_type }};{{ item.service_id }};{{ item.tun_id }};{{ item.comment }}"
      - /interface eoip add name=eoip-{{ item.service_id }}-{{ item.tun_id }} \
        local-address={{ lookup('dig', item.end_node) }} \
        remote-address={{ lookup('dig', item.hub_node) }} \
        tunnel-id={{ item.service_id }}{{ item.tun_id }} \
        mtu=1500 disabled=no \
        comment="{{ item.service_type }};{{ item.service_id }};{{ item.tun_id }};{{ item.comment }}"
      - /interface bridge port add bridge=br-{{ item.service_id }} interface=eoip-{{ item.service_id }}-{{ item.tun_id }}
      - /interface bridge port add bridge=br-{{ item.service_id }} interface={{ item.end_intf }}
  loop: "{{ ros_tunnel }}"
  when:
    - item.type == "eoip"
    - item.state == "present"
    - item.end_node == inventory_hostname


# deploy on hub bridge
- name: eoip_deploy_hub_br
  tags:
    - eoip
  routeros_command:
    commands:
      - /interface eoip add name=eoip-{{ item.service_id }}-{{ item.tun_id }} \
        local-address={{ lookup('dig', item.hub_node) }} \
        remote-address={{ lookup('dig', item.end_node) }} \
        tunnel-id={{ item.service_id }}{{ item.tun_id }} \
        mtu=1500 disabled=no \
        comment="{{ item.service_type }};{{ item.service_id }};{{ item.tun_id }};{{ item.comment }}"
      - /interface bridge port add bridge=br-{{ item.service_id }} interface=eoip-{{ item.service_id }}-{{ item.tun_id }} 
  loop: "{{ ros_tunnel }}"
  when:
    - item.service_type == "br"
    - item.type == "eoip"
    - item.state == "present"
    - item.hub_node == inventory_hostname

# deploy on hub vrf
- name: eoip_deploy_hub_vrf
  tags:
    - eoip
  routeros_command:
    commands:
      - /interface eoip add name=eoip-{{ item.service_id }}-{{ item.tun_id }} \
        local-address={{ lookup('dig', item.hub_node) }} \
        remote-address={{ lookup('dig', item.end_node) }} \
        tunnel-id={{ item.service_id }}{{ item.tun_id }} \
        mtu=1500 disabled=no \
        comment="{{ item.service_type }};{{ item.service_id }};{{ item.tun_id }};{{ item.comment }}"
      - /interface list member add list=vrf{{ item.service_id }} interface=eoip-{{ item.service_id }}-{{ item.tun_id }}
      - /ip address add address={{ item.hub_address }} interface=eoip-{{ item.service_id }}-{{ item.tun_id }}
  loop: "{{ ros_tunnel }}"
  when:
    - item.service_type == "vrf"
    - item.type == "eoip"
    - item.state == "present"
    - item.hub_node == inventory_hostname



