#
# RouterOS tasks
#

# detect version and architecture
- name: get_ros_ver
  tags: detect
  routeros_command:
    commands: ":put [/system resource get version]"
  register: ros_ver

- name: get_ros_arch
  tags: detect
  routeros_command:
    commands: ":put [/system resource get architecture-name]"
  register: ros_arch


- name: ros_upgrade
  tags: upgrade
  import_tasks: roles/routeros/tasks/upgrade.yaml
  when:
    - ros_ver.stdout is search("6\..+")

- name: ros_upgrade7
  tags: upgrade
  import_tasks: roles/routeros/tasks/upgrade7.yaml
  when:
    - ros_ver.stdout is search("7\..+")

- name: ros_eoip
  tags: eoip
  import_tasks: roles/routeros/tasks/eoip.yaml

- name: ros_eoip_ab
  tags: eoip
  import_tasks: roles/routeros/tasks/eoip_ab.yaml

- name: ros_vpls
  tags: vpls
  import_tasks: roles/routeros/tasks/vpls.yaml
  when:
    - ros_ver.stdout is search("6\..+")

- name: ros_vpls7
  tags: vpls
  import_tasks: roles/routeros/tasks/vpls7.yaml
  when:
    - ros_ver.stdout is search("7\..+")

- name: ros_subnet
  tags: subnet
  import_tasks: roles/routeros/tasks/subnet.yaml
  when:
    - ros_ver.stdout is search("6\..+")

- name: ros_subnet7
  tags: subnet
  import_tasks: roles/routeros/tasks/subnet7.yaml
  when:
    - ros_ver.stdout is search("7\..+")


#
# DNS and DHCP
#
- name: ros_dns
  tags: dns
  import_tasks: roles/routeros/tasks/dns.yaml

- name: ros_dhcp
  tags: dhcp
  import_tasks: roles/routeros/tasks/dhcp.yaml


#
#- name: Print the transformed variable
#  ansible.builtin.debug:
#    msg: '{{ item }}'
#  loop: '{{ result.stdout | from_yaml_all | list }}'
#


- name: ros_misc
  tags: misc
  import_tasks: roles/routeros/tasks/misc.yaml



