#
# RouterOS misc tasks
#


- name: ros_users
  tags:
    - users
  routeros_command:
    commands:
      - if [/user get donaldduck ] do={ /user remove donaldduck }
      - if [/user get admin ] do={ :log info "user admin exists" }
      #- /user add name=ansible group=write comment=AnsibleUser password=123
      #- /user add name=backupuser group=read comment=BackupUser password=123


- name: ros_misc
  tags:
    - misc
    - setup
  routeros_command:
    commands:
      - /ip dns set allow-remote-requests=no servers={{ dns_server }}
      - /ip cloud set update-time=no ddns-enabled=no
      - /ip upnp set show-dummy-rule=no enabled=no
      - /ip smb set allow-guests=no enabled=no
      - /ip ssh set allow-none-crypto=no forwarding-enabled=no
      - /tool bandwidth-server set enabled=no
      - /system ntp client set enabled=yes primary-ntp={{ ntp_server1 }} secondary-ntp={{ ntp_server2 }}
      - /system clock set time-zone-autodetect=no time-zone-name={{ timezone }}
      - /ip socks set enabled=no
      - /ip proxy set enabled=no
      - /tool sniffer set enabled=no
      - /ip service set telnet disabled=no
      - /ip service set ftp disabled=yes
      - /ip service set api disabled=yes
      - /ip service set winbox disabled=yes
      - /ip service set api-ssl disabled=yes
      - /snmp community set [ find default=yes ] addresses={{ snmp_allow_from }} name={{ snmp_community }}
      - /snmp set contact={{ snmp_contact }} enabled=yes trap-generators=interfaces trap-interfaces=all trap-target={{ snmp_trap_target }} trap-version=2


- name: ros_mpls
  tags:
    - mpls
  routeros_command:
    commands:
      - /mpls interface set [find where default] mpls-mtu={{ mpls_global_mtu }}
      - /mpls ldp interface set [find] hello-interval=2s hold-time=10s
      - /mpls ldp accept-filter remove [find]
      - /mpls ldp advertise-filter remove [find]
      - /mpls ldp advertise-filter add prefix={{ mpls_loopback_net }}
      - /mpls ldp advertise-filter add prefix=0.0.0.0/0 advertise=no


- name: ros_ospf
  tags: 
    - ospf
  routeros_command:
    commands:
      - /routing ospf interface set [find network-type=point-to-point] \
        hello-interval=2s dead-interval=10s use-bfd=no athentication=md5 authentication-key={{ ospf_auth_key }}


- name: ros_logging
  tags:
    - logging
  routeros_command:
    commands:
      - /system logging action set [find name=remote] remote={{ syslog_server }}
      - /system logging remove [find where !default]
      - /system logging add topics=bfd,info action=memory 
      - /system logging add topics=ospf,info action=memory 
      - /system logging add topics=bgp,info action=memory 


- name: ros_webcert
  tags: 
    - setup
  routeros_command:
    commands:
      - /certificate add name=wwwssl days-valid=768 key-size=4096 common-name={{ inventory_hostname }}
      - /certificate sign [find name name=wwwssl] 
      - /ip service www-ssl certificate=wwwssl disabled=no


- name: ros_firewall
  tags: 
    - fw
  routeros_command:
    commands:
      - /ip firewall service-port set [find] disabled=yes
      - /ip firewall connection tracking set enabled=no
      - /ip firewall filter remove [find comment~"base.+"]
      - /ip firewall address-list add address=192.168.172.0/24 list=g_mgmt
      - /ip firewall address-list add address=192.168.3.0/24 list=g_mgmt
      - /ip firewall address-list add address=172.30.7.0/24 list=g_loopback
      - /ip firewall filter add action=accept chain=input comment=base-ospf protocol=ospf
      - /ip firewall filter add action=accept chain=input comment=base-bfd protocol=udp dst-port=3784,3785
      - /ip firewall filter add action=accept chain=input comment=base-vrrp protocol=vrrp dst-address=224.0.0.18
      - /ip firewall filter add action=accept chain=input comment=base-bgp protocol=tcp port=179 
      - /ip firewall filter add action=accept chain=input comment=base-ldp dst-port=646 protocol=udp
      - /ip firewall filter add action=accept chain=input comment=base-ldp dst-port=646 protocol=tcp
      - /ip firewall filter add action=accept chain=input comment=base-mgmt src-address-list=g_mgmt
      - /ip firewall filter add action=accept chain=input comment=base-eoip protocol=gre src-address-list=g_loopback
      - /ip firewall filter add action=accept chain=input comment=base-vxlan protocol=udp dst-port=4789,8472 src-address-list=g_loopback
      - /ip firewall filter add action=accept chain=input comment=base-mndp dst-address=255.255.255.255 dst-port=5678 protocol=udp src-port=5678
      - /ip firewall filter add action=accept chain=input comment=base-mactel src-address=0.0.0.0 dst-address=255.255.255.255 dst-port=20561 protocol=udp src-port=20561
      - /ip firewall filter add action=accept chain=input comment=base-icmp protocol=icmp
      - /ip firewall filter add action=accept chain=input comment=base-ntp dst-port=123 protocol=udp
      - /ip firewall filter add action=drop chain=input comment=base-drop log-prefix=DROP log=yes


- name: ros_bfd
  tags: 
    - bfd
  routeros_command:
    commands:
      - /routing/ospf/interface-template set [find type=ptp] use-bfd=yes
      - /routing bfd configuration remove [find]
      - /routing bfd configuration add interfaces=ether2
      - /routing bfd configuration add interfaces=ether3


