#
# RouterOS VXLAN tunnel-builder
# Tasks that related to spokes
#
- name: vxlan_config
  tags: vxlan
  include_vars: vars/routeros_vxlan.yaml



# remove on spoke
- name: vxlan_spoke_remove
  tags: vxlan
  routeros_command:
    commands:
      - /interface/bridge/vlan remove [find bridge={{ vxlan_bridge }} vlan-ids={{ item.vni }}]
      - /interface/bridge/port remove [find bridge={{ vxlan_bridge }} interface=vxlan{{ item.vni }}]
      - /interface/bridge/port remove [find bridge={{ vxlan_bridge }} pvid={{ item.vni }}]
      - /interface/vxlan/vteps remove [find name=vxlan{{ item.vni }}]
      - /interface/vxlan remove [find name=vxlan{{ item.vni }}]
  loop: "{{ ros_vxlan }}"
  when:
    - item.state == "absent"
    - item.endpoint == inventory_hostname


# remove spoke on hubs
- name: vxlan_hub_remove_spoke
  tags: vxlan
  routeros_command:
    commands:
      - /interface/vxlan/vteps remove [find name=vxlan{{ item.vni }} remote-ip={{ lookup('dig', item.endpoint) }}]
  loop: "{{ ros_vxlan }}"
  when:
    - item.state == "absent"
    - (vxlan_hub_a == inventory_hostname or vxlan_hub_b == inventory_hostname)



# deploy on spoke
- name: vxlan_spoke_deploy
  tags: vxlan
  routeros_command:
    commands:
      - /interface/vxlan/vteps remove [find interface=vxlan{{ item.vni }}]
      - /interface/bridge add name={{ vxlan_bridge }} vlan-filtering=yes arp=disabled
      - /interface/vxlan add name=vxlan{{ item.vni }} {{ vxlan_options }} \
          local-address={{ lookup('dig', item.endpoint) }} vni={{ item.vni }} \
          comment="{{ item.vni }};{{ item.comment }}"
      - /interface/vxlan/vteps add interface=vxlan{{ item.vni }} remote-ip={{ lookup('dig', vxlan_hub_a) }}
      - /interface/vxlan/vteps add interface=vxlan{{ item.vni }} remote-ip={{ lookup('dig', vxlan_hub_b) }}
      - /interface/bridge/port add bridge={{ vxlan_bridge }} \
          interface=vxlan{{ item.vni }} pvid={{ item.vni }}
      - /interface/bridge/port add bridge={{ vxlan_bridge }} \
          interface={{ item.endpoint_interface }} pvid={{ item.vni }} edge=yes
      - /interface/bridge/vlan add bridge={{ vxlan_bridge }} \
          untagged=vxlan{{ item.vni }},{{ item.endpoint_interface }} vlan-ids={{ item.vni }}
  loop: "{{ ros_vxlan }}"
  when:
    - item.state == "create"
    - item.endpoint == inventory_hostname


# deploy spoke on hubs
- name: vxlan_hub_add_spoke
  tags: vxlan
  routeros_command:
    commands:
      - /interface/vxlan/vteps remove [find interface=vxlan{{ item.vni }} remote-ip={{ lookup('dig', item.endpoint) }}]
      - /interface/vxlan/vteps add interface=vxlan{{ item.vni }} remote-ip={{ lookup('dig', item.endpoint) }}
  loop: "{{ ros_vxlan }}"
  when:
    - item.state == "create"
    - (vxlan_hub_a == inventory_hostname or vxlan_hub_b == inventory_hostname)




