#
# RouterOS VXLAN tunnel-builder 
# Tasks that related to the hubs
#
- name: vxlan_config
  tags: vxlan
  include_vars: vars/routeros_vxlan_hub.yaml



# remove hub configuration
- name: vxlan_hub_remove
  tags: vxlan
  routeros_command:
    commands:
      - /interface/bridge/vlan remove [find bridge={{ item.bridge|default('vxbridge') }} vlan-ids={{ item.bridge_vlan }}]
      - /interface/bridge/port remove [find bridge={{ item.bridge|default('vxbridge') }} interface=vxlan{{ item.vni }}]
      - /interface/bridge/port remove [find bridge={{ item.bridge|default('vxbridge') }} pvid={{ item.vni }}]
      - /interface/vxlan/vteps remove [find name=vxlan{{ item.vni }}]
      - /interface/vxlan remove [find name=vxlan{{ item.vni }}]
  loop: "{{ ros_vxlan_hub }}"
  when:
    - item.state == "absent"
    - (vxlan_hub_a == inventory_hostname or vxlan_hub_b == inventory_hostname)


# Bridge: deploy on hub A
- name: vxlan_hub_deploy_a
  tags: vxlan
  routeros_command:
    commands:
      - /interface/vxlan add name=vxlan{{ item.vni }} {{ vxlan_options }} \
          local-address={{ lookup('dig', inventory_hostname) }} vni={{ item.vni }} \
          comment="{{ item.comment }}"
      - /interface/vxlan/vteps add interface=vxlan{{ item.vni }} {{ vxlan_vtep_options }} \
          remote-ip={{ lookup('dig', vxlan_hub_b) }} \
          comment="{{ vxlan_hub_b }};{{ item.comment }}"
  loop: "{{ ros_vxlan_hub }}"
  when:
    - item.state == "create"
    - vxlan_hub_a == inventory_hostname


# Bridge: deploy on hub B
- name: vxlan_hub_deploy_b
  tags: vxlan
  routeros_command:
    commands:
      - /interface/vxlan add name=vxlan{{ item.vni }} {{ vxlan_options }} \
          local-address={{ lookup('dig', inventory_hostname) }} vni={{ item.vni }} \
          comment="{{ item.comment }}"
      - /interface/vxlan/vteps add interface=vxlan{{ item.vni }} {{ vxlan_vtep_options }} \
          remote-ip={{ lookup('dig', vxlan_hub_a) }} \
          comment="{{ vxlan_hub_a }};{{ item.comment }}"
  loop: "{{ ros_vxlan_hub }}"
  when:
    - item.state == "create"
    - vxlan_hub_b == inventory_hostname



# Bridge: deploy on hub
- name: vxlan_hub_deploy_bridge
  tags: vxlan
  routeros_command:
    commands:
      - /interface/bridge add name={{ item.bridge|default('vxbridge') }} {{ vxlan_bridge_options }}
      - /interface/bridge/port add bridge={{ item.bridge|default('vxbridge') }} interface=vxlan{{ item.vni }} pvid={{ item.bridge_vlan }}
      - /interface/bridge/vlan add bridge={{ item.bridge|default('vxbridge') }} vlan-ids={{ item.bridge_vlan }} untagged=vxlan{{ item.vni }}
  loop: "{{ ros_vxlan_hub }}"
  when:
    - item.state == "create"
    - (vxlan_hub_a == inventory_hostname or vxlan_hub_b == inventory_hostname)




